"""remove_composite_primary_key_add_auto_id

Revision ID: 1b3cde305d7a
Revises: 008b066b1b04
Create Date: 2025-09-13 12:27:14.536428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1b3cde305d7a"
down_revision: Union[str, None] = "008b066b1b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the existing table and recreate with new schema
    op.execute("DROP TABLE bronze_sec_facts;")

    # Create the new table with auto-increment primary key
    op.execute(
        """
        CREATE TABLE bronze_sec_facts (
            id INT AUTO_INCREMENT PRIMARY KEY,
            cik VARCHAR(10) NOT NULL,
            taxonomy VARCHAR(64) NOT NULL,
            tag VARCHAR(256) NOT NULL,
            unit VARCHAR(32) NOT NULL,
            val DECIMAL(20,2) NOT NULL,
            fy DECIMAL(10,0) NULL,
            fp VARCHAR(8) NULL,
            start_date DATE NULL,
            end_date DATE NULL,
            frame VARCHAR(128) NULL,
            form VARCHAR(16) NULL,
            filed DATE NULL,
            accn VARCHAR(32) NULL
        );
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the current table and recreate with old schema
    op.execute("DROP TABLE bronze_sec_facts;")

    # Create the old table with composite primary key
    op.execute(
        """
        CREATE TABLE bronze_sec_facts (
            cik VARCHAR(10) NOT NULL,
            taxonomy VARCHAR(64) NOT NULL,
            tag VARCHAR(256) NOT NULL,
            unit VARCHAR(32) NOT NULL,
            val DECIMAL(20,2) NOT NULL,
            fy DECIMAL(10,0) NULL,
            fp VARCHAR(8) NULL,
            start_date DATE NULL,
            end_date DATE NOT NULL,
            frame VARCHAR(128) NULL,
            form VARCHAR(16) NULL,
            filed DATE NOT NULL,
            accn VARCHAR(32) NOT NULL,
            PRIMARY KEY (cik, taxonomy, tag, unit, end_date, filed, accn)
        );
    """
    )
    # ### end Alembic commands ###
