"""add_filed_as_primary_key

Revision ID: 44ce18d2aed0
Revises: bb70c08cb64e
Create Date: 2025-09-12 18:28:51.443484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44ce18d2aed0"
down_revision: Union[str, None] = "bb70c08cb64e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the existing table
    op.execute("DROP TABLE bronze_sec_facts;")

    # Create the new table with the correct schema
    op.execute(
        """
        CREATE TABLE bronze_sec_facts (
            cik VARCHAR(10) NOT NULL,
            taxonomy VARCHAR(64) NOT NULL,
            tag VARCHAR(256) NOT NULL,
            unit VARCHAR(32) NOT NULL,
            val DECIMAL(20,2) NOT NULL,
            fy DECIMAL(10,0) NULL,
            fp VARCHAR(8) NULL,
            start_date DATE NULL,
            end_date DATE NULL,
            frame VARCHAR(128) NULL,
            form VARCHAR(16) NULL,
            filed DATE NOT NULL,
            accn VARCHAR(32) NOT NULL,
            PRIMARY KEY (cik, taxonomy, tag, unit, filed, accn)
        );
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the current table
    op.execute("DROP TABLE bronze_sec_facts;")

    # Create the table with the original schema
    op.execute(
        """
        CREATE TABLE bronze_sec_facts (
            cik VARCHAR(10) NOT NULL,
            taxonomy VARCHAR(64) NOT NULL,
            tag VARCHAR(256) NOT NULL,
            unit VARCHAR(32) NOT NULL,
            val DECIMAL(20,2) NOT NULL,
            fy DECIMAL(10,0) NULL,
            fp VARCHAR(8) NULL,
            start_date DATE NULL,
            end_date DATE NULL,
            frame VARCHAR(128) NULL,
            form VARCHAR(16) NULL,
            filed DATE NULL,
            accn VARCHAR(32) NOT NULL,
            PRIMARY KEY (cik, taxonomy, tag, unit, accn)
        );
    """
    )
    # ### end Alembic commands ###
