"""increase_cik_column_size_for_cik_prefix

Revision ID: 6c68b7b5f21a
Revises: 1b3cde305d7a
Create Date: 2025-09-13 12:29:44.378905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6c68b7b5f21a"
down_revision: Union[str, None] = "1b3cde305d7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bronze_sec_facts",
        "cik",
        existing_type=mysql.VARCHAR(length=10),
        type_=mysql.VARCHAR(length=13),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bronze_sec_facts",
        "cik",
        existing_type=mysql.VARCHAR(length=13),
        type_=mysql.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
