"""add_submissions_table

Revision ID: c7d4e5f6a8b9
Revises: 0b23c4b77941
Create Date: 2024-09-14 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c7d4e5f6a8b9"
down_revision = "0b23c4b77941"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create facts tables if they don't exist
    op.create_table(
        "bronze_sec_facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cik", sa.String(length=13), nullable=False),
        sa.Column("taxonomy", sa.String(length=64), nullable=False),
        sa.Column("tag", sa.String(length=256), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("val", sa.Numeric(precision=30, scale=2), nullable=False),
        sa.Column("fy", sa.Numeric(), nullable=True),
        sa.Column("fp", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("frame", sa.String(length=128), nullable=True),
        sa.Column("form", sa.String(length=16), nullable=True),
        sa.Column("filed", sa.Date(), nullable=True),
        sa.Column("accn", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "bronze_sec_facts_dict",
        sa.Column("taxonomy", sa.String(length=64), nullable=False),
        sa.Column("tag", sa.String(length=256), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create submissions table
    op.create_table(
        "bronze_sec_submissions",
        sa.Column("cik", sa.String(length=13), nullable=False),
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("acceptance_datetime", sa.DateTime(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("act", sa.Text(), nullable=True),
        sa.Column("form", sa.Text(), nullable=True),
        sa.Column("file_number", sa.Text(), nullable=True),
        sa.Column("film_number", sa.BigInteger(), nullable=True),
        sa.Column("items", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("is_xbrl", sa.Integer(), nullable=True),
        sa.Column("is_inline_xbrl", sa.Integer(), nullable=True),
        sa.Column("primary_document", sa.Text(), nullable=True),
        sa.Column("primary_doc_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint(
            "cik", "accession_number", "filing_date", "acceptance_datetime"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bronze_sec_submissions")
    op.drop_table("bronze_sec_facts_dict")
    op.drop_table("bronze_sec_facts")
    # ### end Alembic commands ###
