"""fix_val_column_precision

Revision ID: e2eba4272c68
Revises: a40b2cf9e7f1
Create Date: 2025-09-12 17:07:17.328702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2eba4272c68'
down_revision: Union[str, None] = 'a40b2cf9e7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bronze_sec_facts', 'val',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bronze_sec_facts', 'val',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
