"""init bronze models

Revision ID: ec6f4f3930e4
Revises:
Create Date: 2025-09-11 15:49:21.698839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec6f4f3930e4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bronze_sec_facts",
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("taxonomy", sa.String(length=64), nullable=False),
        sa.Column("tag", sa.String(length=128), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("val", sa.Numeric(), nullable=False),
        sa.Column("fy", sa.Numeric(), nullable=True),
        sa.Column("fp", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("frame", sa.String(length=128), nullable=True),
        sa.Column("form", sa.String(length=16), nullable=True),
        sa.Column("filed", sa.Date(), nullable=False),
        sa.Column("accn", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("cik", "taxonomy", "tag", "unit", "filed", "accn"),
    )
    op.create_table(
        "bronze_sec_facts_dict",
        sa.Column("taxonomy", sa.String(length=64), nullable=False),
        sa.Column("tag", sa.String(length=128), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("taxonomy", "tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bronze_sec_facts_dict")
    op.drop_table("bronze_sec_facts")
    # ### end Alembic commands ###
